.PHONY: install
install:
	echo '🌞 install frontend dependencies...'; \
	yarn install

.PHONY: build
build:
	echo '🏗  build frontend'; \
	yarn build


.PHONY: run
run:
	echo '🏃 running fronend...'; \
	yarn client
